# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 028b5525470bb116420f137674d32f2f4a4971f58189ffd3564435e13a28610de783e53a8b67a168c2d5e1097b04be5b6cfaa512d956c15b1a25d27a44395254

test:
  secret_key_base: 0286f14dde0490b2d0387458410ac065a96d00e8f32d20b62cf9008fa743261e004b00b9f55a33b0e6cab1e3749cd657effe5f2e128c3cf685a57a128457047d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
